/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backend;
import backend.User;
import java.util.InputMismatchException;
import java.util.Scanner;

public class App {

    static User cliente = new User();

    public static void main(String[] args) {

        try (Scanner teclado = new Scanner(System.in)) {
            
            int num;

            while(true){
                try{
                    System.out.println("1- adicionar");
                    System.out.println("2- atualizar");
                    System.out.println("3- remover");
                    num = teclado.nextInt();
                    opc(num);
                }catch(InputMismatchException e){
                    System.out.println("Entre com um número inteiro");
                    teclado.nextLine();
                }
            }
        }
    }

    private static void opc(int num) {
        switch(num){
            case 1:
                Scanner teclado = new Scanner(System.in);
                System.out.println("Entre com o nome");
                String nome = teclado.nextLine();
                System.out.println("Entre com a senha");
                String senha = teclado.nextLine();
                cliente.adicionar(nome,senha);
                break;
            case 2:
                cliente.atualizar();
                break;
            case 3:
                cliente.remover();
                break;
            default:
                break;
        }
            

    }
}
